services:

  db:
    image: mysql:8.0
    container_name: embedded_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

  wordpress:
    image: wordpress:php8.1-apache
    container_name: embedded_wp
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9000:80"
    volumes:
      - .:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WP_DEBUG: "true"

  wpcli:
    image: wordpress:cli-php8.1
    container_name: embedded_wpcli
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    user: "33:33"
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  db_data:
